sonar.projectKey=port-labs_ocean_github
sonar.organization=port-labs

sonar.python.version=3.9
sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=tests/**/*,**/__init__.py
sonar.test.exclusions=tests/**/* 